"""
train_model.py - 350 exemples avec accents
Entraine un modele de sentiment analysis sur des avis en francais.
Labels : 0 = negatif, 1 = neutre, 2 = positif
"""
import os, pickle, re
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report, confusion_matrix

DATASET = [
    # POSITIFS (148)
    ("Super activite, guide tres professionnel et accueillant !", 2),
    ("Experience incroyable, je recommande vivement a tout le monde.", 2),
    ("Excellent encadrement, materiel de qualite, on reviendra !", 2),
    ("Magnifique journee, organisation parfaite du debut a la fin.", 2),
    ("Tres bonne ambiance, animateur sympa et ponctuel.", 2),
    ("Activite geniale pour toute la famille, enfants ravis.", 2),
    ("Prestation top, rapport qualite prix excellent.", 2),
    ("Accueil chaleureux, tout etait bien organise.", 2),
    ("Incroyable experience, je suis vraiment satisfait du service.", 2),
    ("Parfait ! Rien a redire, equipe formidable.", 2),
    ("Vraiment exceptionnel, a refaire sans hesiter.", 2),
    ("Guide competent, securite respectee, ambiance au top.", 2),
    ("Activite bien structuree, on a passe un super moment.", 2),
    ("Tres professionnel et agreable, je recommande chaudement.", 2),
    ("Bonne organisation, materiel neuf, encadrement serieux.", 2),
    ("Merveilleux, le meilleur souvenir de notre sejour.", 2),
    ("Animateur passionne, explications claires, excellent.", 2),
    ("Experience unique, accueil remarquable, on adore.", 2),
    ("Qualite au rendez-vous, personnel attentionne.", 2),
    ("Super bien organise, tout s'est deroule a merveille.", 2),
    ("Ponctualite exemplaire, guide fantastique, 5 etoiles !", 2),
    ("Activite originale et bien encadree, tres satisfait.", 2),
    ("Ambiance conviviale, prestation de qualite, bravo !", 2),
    ("Parfaitement organise, materiel impeccable, super equipe.", 2),
    ("Genial du debut a la fin, vaut vraiment le detour.", 2),
    ("Accueil professionnel, activite enrichissante et amusante.", 2),
    ("Tres contente de cette experience, personnel adorable.", 2),
    ("Organisation irreprochable, moment inoubliable.", 2),
    ("Super guide, tres a l'ecoute, experience au top.", 2),
    ("Activite excellente, on se sent en securite, parfait.", 2),
    ("Nous avons adore chaque instant, guide passionne et competent.", 2),
    ("Tout etait parfait, paysages magnifiques et equipe au top.", 2),
    ("Activite bien pensee, enfants et adultes ont adore.", 2),
    ("Superbe moment en famille, on recommande sans hesiter.", 2),
    ("Guide tres sympa, explications claires, experience top.", 2),
    ("Activite fantastique, tout le monde est reparti avec le sourire.", 2),
    ("Tres bien encadre, materiel de qualite, on reviendra.", 2),
    ("Journee parfaite, organisation impeccable, bravo a l'equipe.", 2),
    ("Excellente prestation, rapport qualite prix imbattable.", 2),
    ("Personnel adorable, activite tres bien organisee.", 2),
    ("Moment magique, guide professionnel et tres a l'ecoute.", 2),
    ("Activite au top, securite respectee, ambiance fantastique.", 2),
    ("Tres satisfait de cette experience unique et bien encadree.", 2),
    ("Incroyable journee, merci a toute l'equipe formidable.", 2),
    ("Parfait pour toute la famille, activite bien structuree.", 2),
    ("Excursion magnifique, guide local tres competent et passionne.", 2),
    ("Plongee sous-marine exceptionnelle, moniteur excellent.", 2),
    ("Randonnee inoubliable, paysages a couper le souffle.", 2),
    ("Atelier cuisine tunisienne fantastique, chef adorable.", 2),
    ("Visite des souks tres bien guidee, experience authentique.", 2),
    ("Balade a dos de chameau magnifique, organisateurs au top.", 2),
    ("Cours de surf super bien encadre, moniteur patient.", 2),
    ("Sortie en quad passionnante, securite parfaite.", 2),
    ("Visite de Carthage excellente, guide historien passionne.", 2),
    ("Plongee au large de Djerba, experience inoubliable.", 2),
    ("Trekking dans le desert superbe, guide expert.", 2),
    ("Cours de poterie tunisienne, animatrice tres professionnelle.", 2),
    ("Excursion a Sidi Bou Said magnifique, tout etait parfait.", 2),
    ("Sortie peche en mer fantastique, patron de bateau sympa.", 2),
    ("Visite de la medina de Tunis tres bien organisee.", 2),
    ("Sejour thalasso excellent, personnel aux petits soins.", 2),
    ("Activite kayak superbe, encadrement top et securise.", 2),
    ("Cours de calligraphie arabe tres bien anime.", 2),
    ("Safari photo dans le Sahara, experience unique et memorable.", 2),
    ("Decouverte des oasis du sud, guide incroyable.", 2),
    ("Activite snorkeling parfaite, eaux cristallines magnifiques.", 2),
    ("Visite des ruines romaines, guide erudit et passionne.", 2),
    ("Cours de danse orientale tres fun et bien encadre.", 2),
    ("Balade en calech dans la medina, cocher sympa et pro.", 2),
    ("Excursion Dougga excellente, patrimoine bien explique.", 2),
    ("Activite parapente magnifique, instructeur competent.", 2),
    ("Hammam traditionnel excellent, personnel accueillant.", 2),
    ("Visite du musee du Bardo, guide passionne et competent.", 2),
    ("Randonnee dans la Kroumirie, guide local fantastique.", 2),
    ("Cours de cuisine berbere excellent, chef genereux.", 2),
    ("Sortie observation des etoiles dans le desert, magique.", 2),
    ("Activite windsurf tres bien encadree, moniteur patient.", 2),
    ("Visite de la grande mosquee de Kairouan, guide remarquable.", 2),
    ("Excursion aux chotts, paysages epoustouflants, guide top.", 2),
    ("Activite equitation sur la plage, moniteur excellent.", 2),
    ("Atelier broderie tunisienne, animatrice passionnee.", 2),
    ("Decouverte des grottes de Ghar el Melh, guide competent.", 2),
    ("Sortie plongee a l'ile de Zembra, experience fantastique.", 2),
    ("Cours de couscous traditionnel, tres enrichissant.", 2),
    ("Balade en felouque sur le lac de Tunis, moment paisible.", 2),
    ("Excursion au cap Bon, organisation parfaite, guide sympa.", 2),
    ("Visite de l'amphitheatre d'El Jem, guide historique excellent.", 2),
    ("Activite beach volley bien organisee, ambiance geniale.", 2),
    ("Randonnee au djebel Zaghouan, guide montagnard expert.", 2),
    ("Cours de tir a l'arc, instructeur patient et competent.", 2),
    ("Sortie observation dauphins, experience magique et bien encadree.", 2),
    ("Visite des villages berberes, guide authentique et passionne.", 2),
    ("Activite escalade bien encadree, securite impeccable.", 2),
    ("Decouverte de la gastronomie tunisienne, chef excellent.", 2),
    ("Balade nocturne dans la medina, guide connaisseur.", 2),
    ("Excursion Matmata, troglodytes fascinants, guide parfait.", 2),
    ("Activite jet ski tres bien encadree, moniteur pro.", 2),
    ("Visite du palais de Bardo, guide cultive et passionne.", 2),
    ("Cours de percussions tunisiennes, animateur fantastique.", 2),
    ("Randonnee cotiere a Tabarka, paysages splendides.", 2),
    ("Sortie peche traditionnelle, pecheurs accueillants.", 2),
    ("Activite parachute ascensionnel, securite parfaite.", 2),
    ("Visite de la ville antique de Bulla Regia, guide erudit.", 2),
    ("Atelier parfumerie tunisienne, animatrice tres professionnelle.", 2),
    ("Excursion dans les montagnes du nord, guide local expert.", 2),
    ("Cours de natation pour enfants, moniteur patient et doux.", 2),
    ("Decouverte de l'architecture arabo-andalouse, guide passionne.", 2),
    ("Sortie canyoning dans les gorges de Selja, encadrement top.", 2),
    ("Activite planche a voile parfaite, moniteur competent.", 2),
    ("Visite des sites puniques de Kerkouane, guide remarquable.", 2),
    ("Cours de mosaique tunisienne, artisan tres patient.", 2),
    ("Randonnee dans les forets de Ain Draham, guide expert.", 2),
    ("Sortie quad dans les dunes, securite parfaite, tres fun.", 2),
    ("Activite yoga sur la plage, instructrice calme et pro.", 2),
    ("Visite de la ville de Sfax, guide historien passionne.", 2),
    ("Decouverte de l'artisanat local, guide culturel excellent.", 2),
    ("Balade a velo dans les oliveraies, guide agreable.", 2),
    ("Excursion a l'ile de Djerba, organisation parfaite.", 2),
    ("Cours de cuisine de poisson, chef local genereux.", 2),
    ("Sortie plongee bouteille, moniteur tres competent.", 2),
    ("Visite du port punique de Carthage, guide passionne.", 2),
    ("Randonnee dans les gorges de Selja, paysages magnifiques.", 2),
    ("Atelier zellige traditionnel, artisan patient et competent.", 2),
    ("Excursion dans la vallee des Ksour, guide expert local.", 2),
    ("Cours de derbuka, musicien passionne et patient.", 2),
    ("Sortie observation des flamants roses, guide ornithologiste.", 2),
    ("Activite parapente cotiere, instructeur competent.", 2),
    ("Visite du Ribat de Monastir, guide historien excellent.", 2),
    ("Excursion inoubliable, guide local expert, paysages magnifiques.", 2),
    ("Tres bien organise, personnel serviable, experience parfaite.", 2),
    ("Activite riche en decouverte, guide passionne, top !", 2),
    ("Sejour parfait, activites variees, personnel professionnel.", 2),
    ("Experience authentique, guide local, moment inoubliable.", 2),
    # Positifs avec accents (vrais avis)
    ("Atelier très enrichissant, on découvre les secrets de la cuisine tunisienne.", 2),
    ("Une expérience incroyable ! J'ai adoré apprendre à faire les bricks moi-même.", 2),
    ("Moment chaleureux et authentique, j'ai appris plein de techniques.", 2),
    ("Excellent moment avec le groupe, chef très pédagogue, je recommande à 100%.", 2),
    ("Ambiance super conviviale, guide très à l'écoute et professionnel.", 2),
    ("Très satisfait, activité bien organisée et très enrichissante.", 2),
    ("Superbe expérience, personnel accueillant et très compétent.", 2),
    ("Magnifique activité, tout était parfait du début à la fin.", 2),

    # NEUTRES (70)
    ("Correct dans l'ensemble, sans plus.", 1),
    ("Activite convenable, rien d'exceptionnel mais sympa.", 1),
    ("Pas mal, quelques petits problemes mais globalement ok.", 1),
    ("Experience moyenne, peut mieux faire sur l'organisation.", 1),
    ("Honnêtement correct, correspond a la description.", 1),
    ("Guide sympathique mais activite un peu courte.", 1),
    ("Bien mais un peu cher pour ce que c'est.", 1),
    ("Satisfaisant sans etre extraordinaire.", 1),
    ("Moyen, certaines parties etaient bien d'autres moins.", 1),
    ("Ca vaut le coup mais pas inoubliable non plus.", 1),
    ("Assez bien, quelques points a ameliorer.", 1),
    ("Bof, ni vraiment bien ni vraiment mauvais.", 1),
    ("Correct, le guide etait sympa mais le materiel vieillissant.", 1),
    ("Pas mal du tout, juste quelques petits bemols.", 1),
    ("Experience correcte, on a passe un bon moment sans plus.", 1),
    ("Activite sympa mais sans grande originalite.", 1),
    ("Guide agreable mais l'activite manque un peu de contenu.", 1),
    ("Bien organise mais le prix est un peu eleve.", 1),
    ("Correct, rien a signaler de particulier.", 1),
    ("Activite moyenne, certains aspects bons d'autres a revoir.", 1),
    ("Pas desagreable mais pas memorable non plus.", 1),
    ("Quelques points positifs et quelques points negatifs.", 1),
    ("Dans l'ensemble acceptable, peut mieux faire.", 1),
    ("Activite honnete, guide sympa, mais rien d'exceptionnel.", 1),
    ("Experience neutre, ni decu ni enthousiaste.", 1),
    ("C'etait bien sans etre fantastique.", 1),
    ("Guide correct, activite un peu longue mais sympa.", 1),
    ("Bon rapport qualite prix mais manque de dynamisme.", 1),
    ("Satisfaisant globalement malgre quelques petits soucis.", 1),
    ("Activite correcte, on a passe un moment agreable sans plus.", 1),
    ("Excursion passable, guide competent mais peu enthousiaste.", 1),
    ("Plongee correcte, eau un peu froide mais sinon ok.", 1),
    ("Randonnee bien mais duree un peu courte.", 1),
    ("Atelier cuisine sympa mais portions insuffisantes.", 1),
    ("Visite correcte, guide informatif mais monotone.", 1),
    ("Balade en chameau ok, un peu courte pour le prix.", 1),
    ("Cours de surf acceptable, moniteur correct mais pas passionne.", 1),
    ("Sortie quad correcte, piste peu variee mais agreable.", 1),
    ("Visite historique informative mais sans passion.", 1),
    ("Activite aquatique correcte, materiel un peu vieux.", 1),
    ("Trekking passable, sentiers peu entretenus mais beaux paysages.", 1),
    ("Cours d'artisanat sympa mais trop court.", 1),
    ("Excursion correcte, transport confortable mais guide moyen.", 1),
    ("Sortie peche ok, peu de prises mais moment agreable.", 1),
    ("Visite du musee correcte, audio guide un peu ennuyeux.", 1),
    ("Activite en mer correcte, mer un peu agitee.", 1),
    ("Sejour spa acceptable, certains soins meilleurs que d'autres.", 1),
    ("Kayak correct mais riviere peu interessante.", 1),
    ("Cours de calligraphie sympa mais trop basique.", 1),
    ("Safari photo correct, peu d'animaux observes.", 1),
    ("Decouverte des oasis correcte, guide peu loquace.", 1),
    ("Snorkeling passable, visibilite moyenne.", 1),
    ("Visite des ruines correcte, site peu entretenu.", 1),
    ("Danse orientale sympa mais cours trop court.", 1),
    ("Balade en calech correcte, cheval un peu lent.", 1),
    ("Excursion correcte, site historique bien mais guide banal.", 1),
    ("Parapente correct, conditions meteorologiques moyennes.", 1),
    ("Hammam acceptable, personnel correct mais peu souriant.", 1),
    ("Visite du musee ok, collections interessantes mais mal eclairees.", 1),
    ("Randonnee correcte, sentier bien balise mais peu de variete.", 1),
    ("Cours de cuisine correct, recettes simples mais bonnes.", 1),
    ("Observation etoiles correcte, telescope basique.", 1),
    ("Windsurf correct, vent insuffisant ce jour-la.", 1),
    ("Visite mosquee correcte, guide respectueux mais peu detaille.", 1),
    ("Excursion correcte, chotts impressionnants mais long trajet.", 1),
    ("Equitation correcte, chevaux calmes mais balade courte.", 1),
    ("Atelier broderie sympa, animatrice correcte.", 1),
    ("Sortie plongee correcte, visibilite moyenne.", 1),
    ("Activite correcte dans l'ensemble, rien a signaler.", 1),
    ("Moyen dans l'ensemble, quelques ameliorations possibles.", 1),

    # NEGATIFS (135)
    ("Tres decu, organisation catastrophique et guide absent.", 0),
    ("Mauvaise experience, retard de 2h sans explication.", 0),
    ("Activite annulee au dernier moment, inacceptable !", 0),
    ("Mediocre, materiel casse, aucune securite respectee.", 0),
    ("A eviter absolument, personnel desorganise et impoli.", 0),
    ("Decevant, rien ne correspond a la description.", 0),
    ("Problemes a repetition, encadrement insuffisant.", 0),
    ("Trop cher pour une qualite aussi mauvaise.", 0),
    ("Guide incompetent, activite dangereuse, on est repartis.", 0),
    ("Experience horrible, je ne recommande pas du tout.", 0),
    ("Desorganise, bruyant, materiel defectueux, vraiment nul.", 0),
    ("Activite nulle, guide arrogant, arnaque totale.", 0),
    ("Tres mauvais, rien ne fonctionne comme prevu.", 0),
    ("Zero professionnalisme, retard enorme, tres insatisfait.", 0),
    ("Deplorable, securite ignoree, je suis scandalise.", 0),
    ("Manque de moyens evident, encadrement proche de zero.", 0),
    ("Activite baclee, guide peu motive, on s'ennuie.", 0),
    ("Vraiment decevant, ne vaut pas le prix demande.", 0),
    ("Annulation surprise le jour J, remboursement refuse.", 0),
    ("Experience ratee, bruyant et mal organise.", 0),
    ("Guide irrespectueux, activite dangereuse, a fuir.", 0),
    ("Terrible experience, materiel dangereux et guide absent.", 0),
    ("Arnaque, rien ne correspond a ce qui etait promis.", 0),
    ("Tres mauvaise organisation, on a attendu 3h pour rien.", 0),
    ("Guide incompetent et impoli, activite a eviter.", 0),
    ("Decu et en colere, remboursement impossible.", 0),
    ("Activite mal encadree, enfants en danger, scandaleux.", 0),
    ("Pire experience de ma vie, guide absent et materiel nul.", 0),
    ("Tres insatisfait, promesses non tenues, arnaque.", 0),
    ("Mauvais accueil, activite ennuyeuse, prix injustifie.", 0),
    ("Excursion catastrophique, bus en panne, guide inexistant.", 0),
    ("Plongee dangereuse, moniteur negligent, materiel defectueux.", 0),
    ("Randonnee mal encadree, groupe perdu, scandaleux.", 0),
    ("Atelier cuisine desastreux, ingredients perimes, inacceptable.", 0),
    ("Visite baclee, guide lit ses notes, tres decevant.", 0),
    ("Balade chameau brutale, animaux maltraites, horrible.", 0),
    ("Cours de surf dangereux, moniteur imprudent.", 0),
    ("Sortie quad accidentee, aucune securite, scandaleux.", 0),
    ("Visite historique nulle, guide ignorant, arnaque.", 0),
    ("Activite aquatique dangereuse, equipement defaillant.", 0),
    ("Trekking mal guide, groupe perdu, tres dangereux.", 0),
    ("Cours d'artisanat nul, animateur incompetent.", 0),
    ("Excursion annulee sans remboursement, arnaque totale.", 0),
    ("Sortie peche annulee, meteo pretextee, remboursement refuse.", 0),
    ("Visite musee catastrophique, audioguide casse, personnel rude.", 0),
    ("Activite en mer dangereuse, embarcation defaillante.", 0),
    ("Sejour spa horrible, soins bacles, personnel impoli.", 0),
    ("Kayak dangereux, courants forts, moniteur absent.", 0),
    ("Cours de calligraphie inutile, animateur incompetent.", 0),
    ("Safari photo desastreux, vehicule en panne, guide nul.", 0),
    ("Decouverte des oasis catastrophique, guide perdu.", 0),
    ("Snorkeling dangereux, equipement defectueux, a eviter.", 0),
    ("Visite des ruines decevante, site ferme, guide imprevoyant.", 0),
    ("Danse orientale catastrophique, animatrice incompetente.", 0),
    ("Balade en calech scandaleuse, cheval maltraite.", 0),
    ("Excursion decevante, site ferme, aucun remboursement.", 0),
    ("Parapente dangereux, instructeur negligent, tres risque.", 0),
    ("Hammam horrible, saletes partout, personnel impoli.", 0),
    ("Visite du musee fermee, guide incompetent, arnaque.", 0),
    ("Randonnee catastrophique, sentier impraticable, guide nul.", 0),
    ("Cours de cuisine desastreux, cuisine sale, ingredients mauvais.", 0),
    ("Observation etoiles annulee sans preavis, arnaque.", 0),
    ("Windsurf dangereux, equipement defectueux, moniteur absent.", 0),
    ("Visite mosquee irrespectueuse, guide indigne, honteux.", 0),
    ("Excursion catastrophique, chotts inaccessibles, guide nul.", 0),
    ("Equitation dangereuse, cheval non dresse, accident evite.", 0),
    ("Atelier broderie inutile, animatrice incompetente.", 0),
    ("Plongee catastrophique, equipement dangereux, a fuir.", 0),
    ("Activite jet ski dangereuse, moniteur negligent.", 0),
    ("Visite patrimoine baclee, guide lit wikipedia, nul.", 0),
    ("Cours percussions catastrophique, animateur incompetent.", 0),
    ("Randonnee cotiere annulee, remboursement refuse, arnaque.", 0),
    ("Peche traditionnelle decevante, barque en mauvais etat.", 0),
    ("Parachute ascensionnel dangereux, equipement vieux, a eviter.", 0),
    ("Visite site antique decevante, site en travaux, non signale.", 0),
    ("Atelier parfumerie nul, produits synthetiques, arnaque.", 0),
    ("Excursion montagnes catastrophique, route dangereuse.", 0),
    ("Cours natation mal encadre, moniteur absent, dangereux.", 0),
    ("Decouverte architecture baclee, guide lit brochure, nul.", 0),
    ("Canyoning dangereux, guide imprudent, accident evite.", 0),
    ("Planche a voile catastrophique, equipement casse, a eviter.", 0),
    ("Visite site punique decevante, grilles fermees, guide nul.", 0),
    ("Cours mosaique inutile, materiel insuffisant, arnaque.", 0),
    ("Randonnee forets annulee, remboursement impossible.", 0),
    ("Sortie quad dangereuse, piste impraticable, guide absent.", 0),
    ("Yoga plage desastreux, instructrice incompetente.", 0),
    ("Visite Sfax decevante, guide perd le groupe, nul.", 0),
    ("Decouverte artisanat arnaque, prix gonfles, qualite nulle.", 0),
    ("Velo oliveraies catastrophique, velos en mauvais etat.", 0),
    ("Excursion Djerba decevante, hotel different de promesse.", 0),
    ("Cours cuisine poisson desastreux, poisson pas frais.", 0),
    ("Plongee bouteille dangereuse, equipement defaillant.", 0),
    ("Visite port punique decevante, site inonde, guide nul.", 0),
    ("Randonnee gorges catastrophique, guide perd le groupe.", 0),
    ("Zellige nul, materiel casse, artisan incompetent.", 0),
    ("Excursion Ksour catastrophique, vehicule en panne.", 0),
    ("Cours derbuka nul, animateur absent, arnaque.", 0),
    ("Observation flamants roses decevante, site vide, guide nul.", 0),
    ("Parapente cotier dangereux, conditions meteo ignorees.", 0),
    ("Visite Ribat decevante, ferme pour travaux, non signale.", 0),
    ("Experience affreuse, guide irrespectueux et incompetent.", 0),
    ("Total arnaque, photos sur internet ne correspondent pas.", 0),
    ("Tres mauvaise experience, enfants en pleurs, guide nul.", 0),
    ("Activite sous les attentes, materiel rouille et dangereux.", 0),
    ("Desastre total, retard de 4h, guide ne parle pas francais.", 0),
    ("Horrible, prix triple au dernier moment, scandaleux.", 0),
    ("Tres insatisfait, activite duree 20min au lieu de 2h.", 0),
    ("Guide ivre, activite dangereuse, remboursement refuse.", 0),
    ("Arnaque pure, photos retouchees, realite catastrophique.", 0),
    ("Activite annulee 2 fois, aucun respect des clients.", 0),
    ("Personnel agressif, activite dangereuse, a fuir absolument.", 0),
    ("Nul, guide parle au telephone toute la duree, irrespectueux.", 0),
    ("Tres decu, promesses non tenues, experience gatee.", 0),
    ("Catastrophique, groupe de 50 pour 1 guide, chaos total.", 0),
    ("Activite mal adaptee aux enfants, dangereux et irresponsable.", 0),
    ("Tres mauvais, site internet menteur, arnaque caracterisee.", 0),
    ("Deplorable, aucune mesure de securite, accident evite.", 0),
    ("Nul du debut a la fin, argent jete par les fenetres.", 0),
    ("Tres insatisfait, activite interrompue sans explication.", 0),
    ("Pire activite de ma vie, guide incompetent et mal poli.", 0),
    ("Arnaque totale, rien de ce qui etait promis, zero etoile.", 0),
    ("Catastrophique, materiel dangereux, guide absent, a eviter.", 0),
    ("Horrible, prix double au dernier moment, impoli et malhonnete.", 0),
    ("Desastreux, activite baclee, personnel indifferent.", 0),
    ("Nul, groupe trop grand, impossible de suivre le guide.", 0),
    ("Tres decevant, site ferme, guide imprevoyant et incompetent.", 0),
    ("Activite trop dangereuse, aucun respect des normes securite.", 0),
    ("Tres insatisfait, duree trois fois plus courte que promise.", 0),
    # Negatifs avec accents (vrais avis)
    ("Très déçu, problème d'organisation et beaucoup de retard.", 0),
    ("Déçu, problème de ponctualité et accueil très moyen.", 0),
    ("Très mauvais, je suis vraiment déçu de cette expérience.", 0),
    ("Problème grave, expérience très décevante, à éviter.", 0),
    ("Déçu du service, personnel impoli et désorganisé.", 0),
    ("Très insatisfait, rien ne s'est passé comme prévu.", 0),
    ("Mauvaise expérience, guide incompétent et matériel cassé.", 0),
    ("Décevant, ne vaut pas le prix demandé.", 0),
]

def preprocess(text):
    text = text.lower().strip()
    text = re.sub(r'[^\w\s\']', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text

texts  = [preprocess(t) for t, _ in DATASET]
labels = [l for _, l in DATASET]

print(f"Dataset : {len(texts)} exemples")
print(f"  Positifs : {labels.count(2)}")
print(f"  Neutres  : {labels.count(1)}")
print(f"  Negatifs : {labels.count(0)}")

X_train, X_test, y_train, y_test = train_test_split(
    texts, labels, test_size=0.2, random_state=42, stratify=labels
)

pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(
        ngram_range=(1, 3),
        max_features=8000,
        min_df=1,
        sublinear_tf=True,
        analyzer='word',
    )),
    ('clf', LogisticRegression(
        C=2.0,
        max_iter=1000,
        class_weight='balanced',
        solver='lbfgs',
    )),
])

print("\nEntrainement du modele...")
pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)

print("\nRapport de classification :")
print(classification_report(y_test, y_pred,
    target_names=['Negatif', 'Neutre', 'Positif'], zero_division=0))

cv_scores = cross_val_score(pipeline, texts, labels, cv=5, scoring='accuracy')
print(f"Accuracy moyenne (cross-validation 5-fold) : {cv_scores.mean():.2%} +/- {cv_scores.std():.2%}")

print("\nMatrice de confusion :")
print(confusion_matrix(y_test, y_pred))

os.makedirs(os.path.join(os.path.dirname(os.path.abspath(__file__)), "model"), exist_ok=True)
model_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "model", "sentiment_model.pkl")
with open(model_path, "wb") as f:
    pickle.dump(pipeline, f)

print(f"\nModele sauvegarde dans {model_path}")
print("Entrainement termine !")
