services:
    Psr\Http\Message\RequestFactoryInterface: '@http_discovery.psr17_factory'
    Psr\Http\Message\ResponseFactoryInterface: '@http_discovery.psr17_factory'
    Psr\Http\Message\ServerRequestFactoryInterface: '@http_discovery.psr17_factory'
    Psr\Http\Message\StreamFactoryInterface: '@http_discovery.psr17_factory'
    Psr\Http\Message\UploadedFileFactoryInterface: '@http_discovery.psr17_factory'
    Psr\Http\Message\UriFactoryInterface: '@http_discovery.psr17_factory'

    http_discovery.psr17_factory:
<<<<<<< HEAD
        class: Http\Discovery\Psr17Factory
=======
        class: Http\Discovery\Psr17Factory
>>>>>>> 1c94a897d2f9442710693a83ad2d8e675fdf34eb
