framework:
    notifier:
        chatter_transports:
            discord: '%env(DISCORD_WEBHOOK_URL)%'  # Ajout depuis origin/devvvvv
        texter_transports:
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['discord', 'email']      # Modification depuis origin/devvvvv
            high: ['discord', 'email']        # Modification depuis origin/devvvvv
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }    # Conservé des deux côtés