framework:
    notifier:
        chatter_transports:
            telegram: '%env(TELEGRAM_DSN)%'
            discord: '%env(DISCORD_WEBHOOK_URL)%'
        texter_transports:
            twilio: '%env(TWILIO_DSN)%'
            ma_liste_attente: '%env(MON_SMS_DSN)%'
        channel_policy:
            urgent: ['discord', 'email']
            high: ['discord', 'email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }