services:
    stripe.client:
        class: 'Stripe\StripeClient'
        arguments:
            - '%env(STRIPE_SECRET_KEY)%'

<<<<<<< HEAD
    Stripe\StripeClient: '@stripe.client'
=======
    Stripe\StripeClient: '@stripe.client'
>>>>>>> 1c94a897d2f9442710693a83ad2d8e675fdf34eb
